---
dependency:
    name: galaxy
    options:
        role-file: molecule/requirements.yml
        ignore-certs: true
driver:
    name: docker
lint: |
    yamllint .
platforms:
    - name: "${MOLECULE_DISTRO:-centos7}-swarm-master"
      image: "kubecloudsas/docker-ansible-test:${MOLECULE_DISTRO:-centos7}"
      command: ${MOLECULE_DOCKER_COMMAND:-""}
      volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
          - /tmp:/tmp:rw
      privileged: true
      pre_build_image: true
      networks:
          - name: "swarm"
      hostname: "master0"
      published_ports:
          - "0.0.0.0:1330:2377/tcp"
      groups:
          - "swarm_init"
    - name: "${MOLECULE_DISTRO:-centos7}-swarm-slave-01"
      image: "kubecloudsas/docker-ansible-test:${MOLECULE_DISTRO:-centos7}"
      command: ${MOLECULE_DOCKER_COMMAND:-""}
      volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
          - /tmp:/tmp:rw
      privileged: true
      pre_build_image: true
      networks:
          - name: "swarm"
      hostname: "slave1"
      published_ports:
          - "0.0.0.0:1331:2377/tcp"
      groups:
          - "swarm_join"
    - name: "${MOLECULE_DISTRO:-centos7}-swarm-slave-02"
      image: "kubecloudsas/docker-ansible-test:${MOLECULE_DISTRO:-centos7}"
      command: ${MOLECULE_DOCKER_COMMAND:-""}
      volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
          - /tmp:/tmp:rw
      privileged: true
      pre_build_image: true
      networks:
          - name: "swarm"
      hostname: "slave2"
      published_ports:
          - "0.0.0.0:1332:2377/tcp"
      groups:
          - "swarm_join"

provisioner:
    name: ansible
    env:
        ANSIBLE_ROLES_PATH: molecule/roles
    lint:
        name: ansible-lint
        options:
            force-color: true
    playbooks:
        prepare: ${MOLECULE_PREPARE:-molecule-prepare.yml}
        converge: ${MOLECULE_CONVERGE:-molecule-converge.yml}
scenario:
    name: default
    test_sequence:
        - lint
        - dependency
        - syntax
        - destroy
        - create
        - prepare
        - converge
        - side_effect
        - verify
        - cleanup
        - destroy
verifier:
    name: testinfra
    lint:
        name: flake8
